pcm.vendi_mic {
    type plug
    slave {
        pcm "hw:CARD=SF558,DEV=0"
        rate 48000
        channels 1
    }
}

ctl.vendi_mic {
    type hw
    card SF558
}

pcm.vendi_speaker {
    type asym
    playback.pcm {
        type plug
        slave {
            pcm "hw:CARD=Device,DEV=0"
            rate 48000
            channels 2
        }
    }
    hint {
        show on
        description "Vendi USB speaker"
        ioid Output
    }
}
